Michael ayele prefixing prrte binaries
uofl-capstone-open-mpi/prrte pull request #9
Opened 2024-12-03 22:05 UTC by Michael-uofl

Updated Makefile.am files to include @PRTE_BINARY_PREFIX@ in library
and binary names

2024-12-03 22:57 UTC, jsquyres requested changes, later dismissed

2024-12-03 22:57 UTC, jsquyres commented on src/tools/prted/Makefile.am
>      $(prte_libevent_LIBS) \
Missed adding the prefix to the 2 lines above this -- I'll fix.

2024-12-03 22:57 UTC, jsquyres commented on config/prte_configure_options.m4
> +AS_IF([with_prte_binary_prefix=ompi-])
This statement is incorrect (i.e., it's incomplete).  I'll fix.

2024-12-03 22:58 UTC, jsquyres commented on src/Makefile.am
>  libprrte_la_CPPFLAGS =
Missed updating these, too.  I'll fix.

2024-12-03 23:43 UTC, jsquyres commented
* Restored the `prte` command
* Fixed some places where `PRTE_BINARY_PREFIX` was missed
* Fixed a mistake in the `.m4` file
* Took the upstream fix from https://github.com/openpmix/prrte/pull/2087

@hppritcha Please review

2024-12-04 16:24 UTC, hppritcha commented
trying to build this branch and autogen.pl is failing
```
libtoolize: copying file 'config/ltsugar.m4'
libtoolize: copying file 'config/ltversion.m4'
libtoolize: copying file 'config/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --include=config --include=config/oac --force --warnings=all,no-obsolete,no-override
autoreconf: running: /usr/bin/autoheader --include=config --include=config/oac --force --warnings=all,no-obsolete,no-override
autoheader: cannot rename /tmp/aramcX1V/ahjFCanl/config.hin as 
autoheader: 
autoheader:     include/prte_version.h
autoheader: .in: No such file or directory
autoreconf: /usr/bin/autoheader failed with exit status: 1
Command failed: autoreconf -ivf --warnings=all,no-obsolete,no-override -I config -I config/oac
```

2024-12-04 16:53 UTC, hppritcha commented
pushing a small fix to this branch shortly.  Please squash it before merging.

2024-12-04 17:11 UTC, hppritcha approved these changes
I approve assuming the SQUASHME commit is included.

2024-12-04 22:35 UTC, jsquyres commented
@hppritcha There was a standalone commit that made that `configure.ac` change -- I just dropped it (and your SQUASHME).  Should be good now.

2024-12-04 22:42 UTC, merged